import type { Product, Category } from './types';
export const CATEGORIES: Category[] = [
  { id: 'cat1', name: 'Appetizers', slug: 'appetizers' },
  { id: 'cat2', name: 'Main Courses', slug: 'main-courses' },
  { id: 'cat3', name: 'Desserts', slug: 'desserts' },
  { id: 'cat4', name: 'Beverages', slug: 'beverages' },
];
export const PRODUCTS: Product[] = [
  {
    id: 'prod1',
    name: 'Crispy Calamari',
    description: 'Golden-fried calamari served with a zesty marinara sauce.',
    price: 14.99,
    image: 'https://images.unsplash.com/photo-1573821694238-fb3818165a4d?q=80&w=800',
    category: 'appetizers',
    tags: [],
  },
  {
    id: 'prod2',
    name: 'Avocado Toast',
    description: 'Smashed avocado on toasted sourdough with chili flakes.',
    price: 12.50,
    image: 'https://images.unsplash.com/photo-1482049016688-2d3e1b311543?q=80&w=800',
    category: 'appetizers',
    tags: ['Vegetarian'],
  },
  {
    id: 'prod3',
    name: 'Spicy Tuna Rolls',
    description: 'Fresh tuna with spicy mayo, wrapped in seaweed and rice.',
    price: 16.00,
    image: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?q=80&w=800',
    category: 'appetizers',
    tags: ['Spicy'],
  },
  {
    id: 'prod4',
    name: 'Classic Beef Burger',
    description: 'Juicy beef patty with cheddar cheese, lettuce, and tomato.',
    price: 18.99,
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?q=80&w=800',
    category: 'main-courses',
    tags: [],
  },
  {
    id: 'prod5',
    name: 'Grilled Salmon',
    description: 'Perfectly grilled salmon fillet with asparagus and lemon.',
    price: 24.50,
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?q=80&w=800',
    category: 'main-courses',
    tags: ['Gluten-Free'],
  },
  {
    id: 'prod6',
    name: 'Vegan Buddha Bowl',
    description: 'A healthy mix of quinoa, roasted vegetables, and tahini dressing.',
    price: 17.00,
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?q=80&w=800',
    category: 'main-courses',
    tags: ['Vegan', 'Vegetarian', 'Gluten-Free'],
  },
  {
    id: 'prod7',
    name: 'Margherita Pizza',
    description: 'Classic pizza with fresh mozzarella, tomatoes, and basil.',
    price: 15.99,
    image: 'https://images.unsplash.com/photo-1598021680942-8aa3b21f3666?q=80&w=800',
    category: 'main-courses',
    tags: ['Vegetarian'],
  },
  {
    id: 'prod8',
    name: 'Spicy Thai Green Curry',
    description: 'Aromatic green curry with chicken, bamboo shoots, and coconut milk.',
    price: 19.50,
    image: 'https://images.unsplash.com/photo-1628579325091-d8728553911a?q=80&w=800',
    category: 'main-courses',
    tags: ['Spicy', 'Gluten-Free'],
  },
  {
    id: 'prod9',
    name: 'Chocolate Lava Cake',
    description: 'Warm chocolate cake with a gooey molten center, served with vanilla ice cream.',
    price: 10.99,
    image: 'https://images.unsplash.com/photo-1586985289936-a8a7b3534833?q=80&w=800',
    category: 'desserts',
    tags: ['Vegetarian'],
  },
  {
    id: 'prod10',
    name: 'New York Cheesecake',
    description: 'Creamy and rich cheesecake with a graham cracker crust.',
    price: 9.50,
    image: 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?q=80&w=800',
    category: 'desserts',
    tags: ['Vegetarian'],
  },
  {
    id: 'prod11',
    name: 'Fresh Fruit Sorbet',
    description: 'A refreshing trio of mango, raspberry, and lemon sorbet.',
    price: 8.00,
    image: 'https://images.unsplash.com/photo-1615478503562-ec2d8aa0e24e?q=80&w=800',
    category: 'desserts',
    tags: ['Vegan', 'Vegetarian', 'Gluten-Free'],
  },
  {
    id: 'prod12',
    name: 'Iced Latte',
    description: 'Chilled espresso with milk, served over ice.',
    price: 5.50,
    image: 'https://images.unsplash.com/photo-1517701550927-20c55d513a9a?q=80&w=800',
    category: 'beverages',
    tags: ['Vegetarian'],
  },
];